// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIN6QiMLva_M2DJqQb2X12eGP-Y1c7kaA',
    appId: '1:565095371455:web:fbc78cbbf95a631cd8ec0a',
    messagingSenderId: '565095371455',
    projectId: 'coursewk6-f1f20',
    authDomain: 'coursewk6-f1f20.firebaseapp.com',
    storageBucket: 'coursewk6-f1f20.firebasestorage.app',
    measurementId: 'G-01HTHKB1MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktbKHfzmpBOyRQQ3jmdHzVOEylqfeXvs',
    appId: '1:565095371455:android:708d3a11e4e4a7d7d8ec0a',
    messagingSenderId: '565095371455',
    projectId: 'coursewk6-f1f20',
    storageBucket: 'coursewk6-f1f20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVefNJpLL2WLnA4d3g62yyqqQ3-VWROwE',
    appId: '1:565095371455:ios:275f7ee0b51d4d89d8ec0a',
    messagingSenderId: '565095371455',
    projectId: 'coursewk6-f1f20',
    storageBucket: 'coursewk6-f1f20.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVefNJpLL2WLnA4d3g62yyqqQ3-VWROwE',
    appId: '1:565095371455:ios:275f7ee0b51d4d89d8ec0a',
    messagingSenderId: '565095371455',
    projectId: 'coursewk6-f1f20',
    storageBucket: 'coursewk6-f1f20.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIN6QiMLva_M2DJqQb2X12eGP-Y1c7kaA',
    appId: '1:565095371455:web:1cb503ce0dd75dddd8ec0a',
    messagingSenderId: '565095371455',
    projectId: 'coursewk6-f1f20',
    authDomain: 'coursewk6-f1f20.firebaseapp.com',
    storageBucket: 'coursewk6-f1f20.firebasestorage.app',
    measurementId: 'G-JHBYH6SBQC',
  );
}
